### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by twinaphex** [libretro/libretro-crocods#1]
Submodules make it really hard to integrate this into our libretro-super workflow.

Git submodules are fundamentally broken in many ways. I think it would be best instead to just have a local snapshot of crocods-core instead, and just manually update that from time to time when it's necessary.

I don't want to deal with git submodules, it's a disaster in many respects and it will not integrate well with libretro-super. Best thing to do is to simply avoid it. For all its faults, submodules is something that hg/subversion actually did well (but sadly it did everything else far worse than git).

**Comment by twinaphex** [comment]
As a further addendum, I had to get rid of the submodule in pocketcdg due to running into the same issues. And I think for a single file, it might be best to just put it in the main repo anyway.

**Comment by redbug26** [comment]
Ok. I remove sub module dependency.

**Comment by twinaphex** [comment]
Thanks very much! This will make it much easier to deploy on the buildbot.
