### ISSUE TITLE
Permission to add crocoDS to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by twinaphex** [libretro/libretro-crocods#8]
Hi @redbug26,

we would like to seek your permission to include crocoDS as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by redbug26** [comment]
No problem

**Comment by twinaphex** [comment]
Thank you!

**Comment by LibretroAdmin** [comment]
@redbug26 It took a while but it has finally been added!

https://store.steampowered.com/news/app/1118310/view/3356884419721245718
